### ISSUE TITLE
jsBabelOverride

### ISSUE THREAD

**Issue by code-flow** [swashata/wp-webpack-script#692]
Hey there, and first: thanks for the great project you've created.

I'm currently struggling with the wpackio.project.js file. Especially with the `jsBabelOverride` attribute. I wanted to integrate the [@wordpress/babel-plugin-makepot](https://www.npmjs.com/package/@wordpress/babel-plugin-makepot) but it seems that it's not executed.

This is the file I'm currently working with:

```
module.exports = {
	...
	useBabelConfig     : false,
	// Hook into babeloverride so that we can add react-hot-loader plugin
	jsBabelOverride    : defaults => {
		return {
			...defaults,
			plugins: [
				[ '@wordpress/babel-plugin-makepot', {
					output: 'myplugin.pot'
				} ],
				'react-hot-loader/babel',
			],
		};
	},
};
```

Can anyone help on this?

**Comment by adiosneo** [comment]
Hi, I have the very same issue. The bug is that `jsBabelOverride` nor `

**Comment by adiosneo** [comment]
Hi, I have the very same issue. The bug is that `jsBabelOverride` nor `jsBabelPresetOptions` and their equivalencies for TypeScript aren't passed to the function that is creating a webpack config: [CreateWebpackConfig.ts#L160](https://github.com/swashata/wp-webpack-script/blob/master/packages/scripts/src/config/CreateWebpackConfig.ts#L160)

On line 160th, the second argument is a configuration which as you can see doesn't contain all of the properties so, when it will come to the [getModule()](https://github.com/swashata/wp-webpack-script/blob/master/packages/scripts/src/config/WebpackConfigHelper.ts#L417) method it will come out that `this.config.jsBabelOverride` and `this.config.jsBabelPresetOptions` are `undefined`.

**Comment by swashata** [comment]
Thank you @adiosneo for the quick debug. I will publish a fix with the next version.
